Sequel.migration do
	up do

    # Insert types
    self[:types].insert(:id =>   0, :name => 'Unspecified') 
    self[:types].insert(:id =>   1, :name => 'Unspecified') 
    self[:types].insert(:id =>   2, :name => 'Wing in Grnd') 
    self[:types].insert(:id =>   3, :name => 'Other') 
    self[:types].insert(:id =>   4, :name => 'High Speed Craft') 
    self[:types].insert(:id =>   5, :name => 'Other') 
    self[:types].insert(:id =>   6, :name => 'Passenger') 
    self[:types].insert(:id =>   7, :name => 'Cargo') 
    self[:types].insert(:id =>   8, :name => 'Tanker') 
    self[:types].insert(:id =>   9, :name => 'Unspecified') 
    self[:types].insert(:id =>   10, :name => 'Reserved') 
    self[:types].insert(:id =>   11, :name => 'Reserved') 
    self[:types].insert(:id =>   12, :name => 'Reserved') 
    self[:types].insert(:id =>   13, :name => 'Reserved') 
    self[:types].insert(:id =>   14, :name => 'Reserved') 
    self[:types].insert(:id =>   15, :name => 'Reserved') 
    self[:types].insert(:id =>   16, :name => 'Reserved') 
    self[:types].insert(:id =>   17, :name => 'Reserved') 
    self[:types].insert(:id =>   18, :name => 'Reserved') 
    self[:types].insert(:id =>   19, :name => 'Reserved') 
    self[:types].insert(:id =>   20, :name => 'Wing In Grnd') 
    self[:types].insert(:id =>   21, :name => 'Wing In Grnd') 
    self[:types].insert(:id =>   22, :name => 'Wing In Grnd') 
    self[:types].insert(:id =>   23, :name => 'Wing In Grnd') 
    self[:types].insert(:id =>   24, :name => 'Wing In Grnd') 
    self[:types].insert(:id =>   25, :name => 'Wing In Grnd') 
    self[:types].insert(:id =>   26, :name => 'Wing In Grnd') 
    self[:types].insert(:id =>   27, :name => 'Wing In Grnd') 
    self[:types].insert(:id =>   28, :name => 'Wing In Grnd') 
    self[:types].insert(:id =>   29, :name => 'SAR Aircraft') 
    self[:types].insert(:id =>   30, :name => 'Fishing') 
    self[:types].insert(:id =>   31, :name => 'Tug') 
    self[:types].insert(:id =>   32, :name => 'Tug') 
    self[:types].insert(:id =>   33, :name => 'Dredger') 
    self[:types].insert(:id =>   34, :name => 'Dive Vessel') 
    self[:types].insert(:id =>   35, :name => 'Military Ops') 
    self[:types].insert(:id =>   36, :name => 'Sailing Vessel') 
    self[:types].insert(:id =>   37, :name => 'Pleasure Craft') 
    self[:types].insert(:id =>   38, :name => 'Reserved') 
    self[:types].insert(:id =>   39, :name => 'Reserved') 
    self[:types].insert(:id =>   40, :name => 'High Speed Craft') 
    self[:types].insert(:id =>   41, :name => 'High Speed Craft') 
    self[:types].insert(:id =>   42, :name => 'High Speed Craft') 
    self[:types].insert(:id =>   43, :name => 'High Speed Craft') 
    self[:types].insert(:id =>   44, :name => 'High Speed Craft') 
    self[:types].insert(:id =>   45, :name => 'High Speed Craft') 
    self[:types].insert(:id =>   46, :name => 'High Speed Craft') 
    self[:types].insert(:id =>   47, :name => 'High Speed Craft') 
    self[:types].insert(:id =>   48, :name => 'High Speed Craft') 
    self[:types].insert(:id =>   49, :name => 'High Speed Craft') 
    self[:types].insert(:id =>   50, :name => 'Pilot Vessel') 
    self[:types].insert(:id =>   51, :name => 'SAR') 
    self[:types].insert(:id =>   52, :name => 'Tug') 
    self[:types].insert(:id =>   53, :name => 'Port Tender') 
    self[:types].insert(:id =>   54, :name => 'Anti-Pollution') 
    self[:types].insert(:id =>   55, :name => 'Law Enforce') 
    self[:types].insert(:id =>   56, :name => 'Local Vessel') 
    self[:types].insert(:id =>   57, :name => 'Local Vessel') 
    self[:types].insert(:id =>   58, :name => 'Medical Trans') 
    self[:types].insert(:id =>   59, :name => 'Special Craft') 
    self[:types].insert(:id =>   60, :name => 'Passenger') 
    self[:types].insert(:id =>   61, :name => 'Passenger') 
    self[:types].insert(:id =>   62, :name => 'Passenger') 
    self[:types].insert(:id =>   63, :name => 'Passenger') 
    self[:types].insert(:id =>   64, :name => 'Passenger') 
    self[:types].insert(:id =>   65, :name => 'Passenger') 
    self[:types].insert(:id =>   66, :name => 'Passenger') 
    self[:types].insert(:id =>   67, :name => 'Passenger') 
    self[:types].insert(:id =>   68, :name => 'Passenger') 
    self[:types].insert(:id =>   69, :name => 'Passenger') 
    self[:types].insert(:id =>   70, :name => 'Cargo') 
    self[:types].insert(:id =>   71, :name => 'Cargo - Hazard A (Major)') 
    self[:types].insert(:id =>   72, :name => 'Cargo - Hazard B') 
    self[:types].insert(:id =>   73, :name => 'Cargo - Hazard C (Minor)') 
    self[:types].insert(:id =>   74, :name => 'Cargo - Hazard D (Recognizable)') 
    self[:types].insert(:id =>   75, :name => 'Cargo') 
    self[:types].insert(:id =>   76, :name => 'Cargo') 
    self[:types].insert(:id =>   77, :name => 'Cargo') 
    self[:types].insert(:id =>   78, :name => 'Cargo') 
    self[:types].insert(:id =>   79, :name => 'Cargo') 
    self[:types].insert(:id =>   80, :name => 'Tanker') 
    self[:types].insert(:id =>   81, :name => 'Tanker - Hazard A (Major)') 
    self[:types].insert(:id =>   82, :name => 'Tanker - Hazard B') 
    self[:types].insert(:id =>   83, :name => 'Tanker - Hazard C (Minor)') 
    self[:types].insert(:id =>   84, :name => 'Tanker - Hazard D (Recognizable)') 
    self[:types].insert(:id =>   85, :name => 'Tanker') 
    self[:types].insert(:id =>   86, :name => 'Tanker') 
    self[:types].insert(:id =>   87, :name => 'Tanker') 
    self[:types].insert(:id =>   88, :name => 'Tanker') 
    self[:types].insert(:id =>   89, :name => 'Tanker') 
    self[:types].insert(:id =>   90, :name => 'Other') 
    self[:types].insert(:id =>   91, :name => 'Other') 
    self[:types].insert(:id =>   92, :name => 'Other') 
    self[:types].insert(:id =>   93, :name => 'Other') 
    self[:types].insert(:id =>   94, :name => 'Other') 
    self[:types].insert(:id =>   95, :name => 'Other') 
    self[:types].insert(:id =>   96, :name => 'Other') 
    self[:types].insert(:id =>   97, :name => 'Other') 
    self[:types].insert(:id =>   98, :name => 'Other') 
    self[:types].insert(:id =>   99, :name => 'Other') 
    self[:types].insert(:id =>   100, :name => 'Navigation Aid') 
    self[:types].insert(:id =>   101, :name => 'Reference Point') 
    self[:types].insert(:id =>   102, :name => 'RACON') 
    self[:types].insert(:id =>   103, :name => 'Off Shore Structure') 
    self[:types].insert(:id =>   104, :name => 'Spare') 
    self[:types].insert(:id =>   105, :name => 'Light, without Sectors') 
    self[:types].insert(:id =>   106, :name => 'Light, with Sectors') 
    self[:types].insert(:id =>   107, :name => 'Leading Light Front') 
    self[:types].insert(:id =>   108, :name => 'Leading Light Rear') 
    self[:types].insert(:id =>   109, :name => 'Beacon, Cardinal N') 
    self[:types].insert(:id =>   110, :name => 'Beacon, Cardinal E') 
    self[:types].insert(:id =>   111, :name => 'Beacon, Cardinal S') 
    self[:types].insert(:id =>   112, :name => 'Beacon, Cardinal W') 
    self[:types].insert(:id =>   113, :name => 'Beacon, Port Hand') 
    self[:types].insert(:id =>   114, :name => 'Beacon, Starboard Hand') 
    self[:types].insert(:id =>   115, :name => 'Beacon, Preferred Channel Port hand') 
    self[:types].insert(:id =>   116, :name => 'Beacon, Preferred Channel Starboard hand') 
    self[:types].insert(:id =>   117, :name => 'Beacon, Isolated danger') 
    self[:types].insert(:id =>   118, :name => 'Beacon, Safe Water') 
    self[:types].insert(:id =>   119, :name => 'Beacon, Special Mark') 
    self[:types].insert(:id =>   120, :name => 'Cardinal Mark N') 
    self[:types].insert(:id =>   121, :name => 'Cardinal Mark E') 
    self[:types].insert(:id =>   122, :name => 'Cardinal Mark S') 
    self[:types].insert(:id =>   123, :name => 'Cardinal Mark W') 
    self[:types].insert(:id =>   124, :name => 'Port Hand Mark') 
    self[:types].insert(:id =>   125, :name => 'Starboard Hand Mark') 
    self[:types].insert(:id =>   126, :name => 'Preferred Channel Port Hand') 
    self[:types].insert(:id =>   127, :name => 'Preferred Channel Starboard Hand') 
    self[:types].insert(:id =>   128, :name => 'Isolated Danger') 
    self[:types].insert(:id =>   129, :name => 'Safe Water') 
    self[:types].insert(:id =>   130, :name => 'Manned VTS') 
    self[:types].insert(:id =>   131, :name => 'Light Vessel') 
   
  end

  down do
    DB[:types].truncate
  end
  
end

